<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Opx.HttpClient</AssemblyName>
    <RootNamespace>Opx.Http</RootNamespace>
    <Title>Opx.HttpClient</Title>
    <Authors>Noviyanto Wibowo</Authors>
    <Description>HTTP Client Helper :
Read JSON (API) to Any&lt;T&gt;, Read content from web page,
support HTTP 2 &amp; 3, Async &amp; Sync supported</Description>
    <Copyright>© 2024, Noviyanto Wibowo</Copyright>
    <PackageIcon>logo.png</PackageIcon>
    <PackageTags>http;httpclient;</PackageTags>
    <Version>1.0.9</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
